export const GET_ALL_TODOTASK = 'GET_ALL_TODOTASK';
export const CREATE_NEW_TODOTASK = 'CREATE_NEW_TODOTASK';
//ACTION TO REMOVE THE CONTACT LIST
export const EDIT_TODOTASK = 'EDIT_TODOTASK';
export const REMOVE_TODOTASK = 'REMOVE_TODOTASK';

  